### ISSUE TITLE
[BUG] Exception on Server Shutdown

### ISSUE THREAD

**Issue by Velyn-N** [Lorias-Jak/LoriTime#176] opened 2024-10-22 17:48 UTC
## Describe the bug
When shutting down the Server an Exception occurs

## Steps to reproduce
- Have a Paper Server (1.21 in my case)
- Have LoriTime (Bukkit)
- Stop the Server gracefully

## Expected behavior
No Exception

## Screenshots
Even better: A Strack Trace!
```
[17:34:22 INFO]: [LoriTimeBukkit] Disabling LoriTimeBukkit v1.5.0
[17:34:22 INFO]: [LoriTimeBukkit] Stopping Update-Check Task!
[17:34:22 INFO]: [LoriTimeBukkit] Closing connection to (database, 3306 ,bauserver)...
[17:34:22 INFO]: [com.jannik_kuehn.dependencies.com.zaxxer.hikari.HikariDataSource] LoriTime-Databasepool - Shutdown initiated...
[17:34:22 INFO]: [com.jannik_kuehn.dependencies.com.zaxxer.hikari.HikariDataSource] LoriTime-Databasepool - Shutdown completed.
[17:34:22 INFO]: [LoriTimeBukkit] Successfully closed the connection to the MySQL-Server!
[17:34:22 ERROR]: [LoriTimeBukkit] An exception occurred while closing the timeStorage
com.jannik_kuehn.common.exception.StorageException: java.sql.SQLException: HikariDataSource is not initialized.
       at LoriTimeBukkit.jar/com.jannik_kuehn.common.storage.database.DatabaseStorage.addTimes(DatabaseStorage.java:206) ~[LoriTimeBukkit.jar:?]
       at LoriTimeBukkit.jar/com.jannik_kuehn.common.api.storage.AccumulatingTimeStorage.close(AccumulatingTimeStorage.java:112) ~[LoriTimeBukkit.jar:?]
       at LoriTimeBukkit.jar/com.jannik_kuehn.common.storage.DataStorageManager.closeStorages(DataStorageManager.java:166) ~[LoriTimeBukkit.jar:?]
       at LoriTimeBukkit.jar/com.jannik_kuehn.common.LoriTimePlugin.disable(LoriTimePlugin.java:135) ~[LoriTimeBukkit.jar:?]
       at LoriTimeBukkit.jar/com.jannik_kuehn.loritimebukkit.LoriTimeBukkit.onDisable(LoriTimeBukkit.java:109) ~[LoriTimeBukkit.jar:?]
       at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
       at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
       at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:161) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
       at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:97) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
       at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:541) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
       at org.bukkit.craftbukkit.CraftServer.disablePlugins(CraftServer.java:610) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
       at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:1045) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
       at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:847) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
       at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1351) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
       at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
       at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.sql.SQLException: HikariDataSource is not initialized.
       at LoriTimeBukkit.jar/com.jannik_kuehn.common.storage.database.MySQL.getConnection(MySQL.java:113) ~[LoriTimeBukkit.jar:?]
       at LoriTimeBukkit.jar/com.jannik_kuehn.common.storage.database.DatabaseStorage.addTimes(DatabaseStorage.java:202) ~[LoriTimeBukkit.jar:?]
       ... 15 more
```

## Server (please complete the following information):
- OS: Linux (Docker)
- Server Software: Paper 1.21 (1.21.1-128-master)
- LoriTime Bukkit 1.5.0

Btw, there is no /lta info Command as named in the GitHub Bug Template

## Additional context
-/-

**Comment by Lorias-Jak** [comment] 2024-11-29 15:48
I cant reproduce the issue. As of that, I will close the issue. Feel free to reply if youre getting the issue again.

**Closed by Lorias-Jak** 2024-11-29 15:48 UTC
Labels: bug
